iOS: Adds ability to handle DTMF codes in Callkit
hoxfon/react-native-twilio-programmable-voice pull request #160
Opened 2020-10-28 12:57 UTC by fmonsalvo

This PR adds a handler to manage DTMF codes in Call Kit.

2020-10-28 13:00 UTC, jdegger commented
@fmonsalvo Looking good, the code looks fairly straight forward, I have not tested it yes but will soon. Thanks. I have also requested review from @fabriziomoscon

2020-10-29 07:56 UTC, fabriziomoscon requested changes
change the log

2020-10-29 07:56 UTC, fabriziomoscon commented on ios/RNTwilioVoice/RNTwilioVoice.m
> +    RCTLogInfo(@"SendDigits %@", action.digits);
We haven't used `RCTLogInfo()` so far. I would suggest to stick to `NSLog()`.
If you see advantages that I am not aware of by using `RCTLogInfo()`, please open another PR that changes all the occurrences of `NSLog()`

2020-10-30 16:50 UTC, fmonsalvo commented
@fabriziomoscon just changed the line to use NSLog, please review it.

2020-11-03 08:30 UTC, merged