Fixed bug on unregistration (ios)
hoxfon/react-native-twilio-programmable-voice pull request #194
Opened 2021-04-05 09:19 UTC by ro-mgh

Hi guys!

We faced with the following issue: when TwilioVoice.unregister() is called we are not able to register the device again with TwilioVoice.initWithToken(). 

I found out that it happens because when we try to register device again, we compare if cachedDeviceToken has changed versus actual deviceTokenString. And we are able to register PushNotifications only if our Device tokes was changed.

...
(line 245 in RNTwilioVoice.m) if (![cachedDeviceToken isEqualToString:deviceTokenString]) {
...

But when we unregister the device we are not changing the cached token in memory, so when we try to register Pushes again, library compare the cashed token (which was not changed) vs actual deviceTokenString (which is still the same as well). As a result we are not able to register Push notifications.

Proposed solution: when TwilioVoice.unregister() is called, and the unregistration was successfull, we should clear the cashed device token. It allows us to register device again.

Hope you will reply soon.
Roma

2021-04-06 09:38 UTC, jdegger commented
Thank you for your PR(s)! We will test and review them ASAP.

2021-04-06 18:35 UTC, fabriziomoscon commented on ios/RNTwilioVoice/RNTwilioVoice.m
> +                                      [[NSUserDefaults standardUserDefaults] setValue:@"" forKey:kCachedDeviceToken];
indent

2021-04-08 06:20 UTC, jdegger requested changes

2021-04-08 06:20 UTC, jdegger commented on ios/RNTwilioVoice/RNTwilioVoice.m
> +                                      [[NSUserDefaults standardUserDefaults] setValue:@"" forKey:kCachedDeviceToken];
```suggestion
                                        [[NSUserDefaults standardUserDefaults] setValue:@"" forKey:kCachedDeviceToken];
```

2021-04-08 06:20 UTC, jdegger commented
@fabriziomoscon i have fixed the indentation

2021-04-10 15:44 UTC, fabriziomoscon commented
@ro-mgh is this PR applicable #164 ?

2021-07-12 21:00 UTC, ro-mgh commented
Changes included to https://github.com/hoxfon/react-native-twilio-programmable-voice/pull/205 PR against sdk-5

2021-07-13 20:22 UTC, closed without merging

2022-06-14 05:38 UTC, tragicmj commented
@ro-mgh Unregistration not working in iOS, can you please have a look once.

2022-06-14 21:58 UTC, ro-mgh commented
@tragicmj , I think that is because changes from this PR was somehow lost in the main branch, you could use patch package and implement them manually)

2022-06-15 08:03 UTC, tragicmj commented
@ro-mgh thanks for your reply. Facing one issue
![Simulator Screen Shot - iPhone 11 - 2022-06-08 at 14 24 40](https://user-images.githubusercontent.com/44090234/173775070-6fac419e-a6ef-436e-81ed-e4fa24d10220.png)
 Any way to remove the black outline circle (the green background coming up on top left) after the call is disconnected by the other end in an outbound call??