draft
hoxfon/react-native-twilio-programmable-voice pull request #197
Opened 2021-04-07 22:46 UTC by fabriziomoscon

2021-04-07 23:14 UTC, fabriziomoscon commented
@jdegger could you please review this? And suggest if I missed something.
I want to add this section to save time explaining the future plans in various issues.

2021-04-08 06:17 UTC, jdegger requested changes
Two minor clarifications

2021-04-08 06:17 UTC, jdegger commented on README.md
> +```
```suggestion
```bash
# Yarn
yarn add https://github.com/hoxfon/react-native-twilio-programmable-voice#feat/twilio-android-sdk-5

# NPM
npm install git+https://github.com/hoxfon/react-native-twilio-programmable-voice#feat/twilio-android-sdk-5
```
```

2021-04-08 06:17 UTC, jdegger commented on README.md
> +_If you want to contribute please consider helping on this project._
```suggestion
_If you want to contribute please consider helping on this project. [Click here for more information](https://github.com/hoxfon/react-native-twilio-programmable-voice/issues/158)._
```

2021-04-08 09:55 UTC, fabriziomoscon commented
@jdegger I committed your changes. Could you approve?

2021-04-08 10:32 UTC, jdegger approved these changes

2021-04-08 10:32 UTC, jdegger commented
@fabriziomoscon 👍

2021-04-08 11:47 UTC, merged